---
dist: xenial
language: python
python: 3.7

before_install:
  - sudo pip install tox==3.8.6
  - wget https://dl.min.io/server/minio/release/linux-amd64/minio
  - sudo chmod +x minio && sudo mv minio /usr/bin

script: tox
